export const ADD_ELEM = 'ADD_ELEM'
export const ADD_PHOTO_ELEM = 'ADD_PHOTO_ELEM'
export const DELETE_ELEM = 'DELETE_ELEM'
export const COPY_ELEM = 'COPY_ELEM'
export const ADD_CONTENT_IN_ELEM = 'ADD_CONTENT_IN_ELEM'
export const COPY_PHOTO_ELEM = 'COPY_PHOTO_ELEM'
export const DOWNLOAD_PHOTO = "DOWNLOAD_PHOTO"
export const SWAP_ELEMS = "SWAP_ELEMS"